### ISSUE TITLE
augment images and masks using flow (keyerro 'image')

### ISSUE THREAD

**Issue by ggous** [mjkvaak/ImageDataAugmentor#16]
Hi, is it possible to augment images and masks using `flow` instead of using `flow_from_directory`? 

I am using this:

```
 img_data_gen = ImageDataAugmentor(
        augment=AUGMENTATIONS, 
        input_augment_mode='image', 
        seed=seed,
        validation_split=0.2,
    )
    mask_data_gen = ImageDataAugmentor(
        augment=AUGMENTATIONS, 
        input_augment_mode='mask', 
        preprocess_input=one_hot_encode_masks,
        seed=seed,
        validation_split=0.2,
    )

 img_data_gen.fit(X, augment=True)
    train_img_gen = img_data_gen.flow(X, batch_size=batch_size, subset='training')
    
    mask_data_gen.fit(y, augment=True)
    train_mask_gen = mask_data_gen.flow(y, batch_size=batch_size, sudset='training')
    
    train_generator = zip(train_img_gen, train_mask_gen)
    

    img_data_gen.fit(X, augment=True)
    val_img_gen = img_data_gen.flow(X, batch_size=batch_size, subset='validation')
    
    mask_data_gen.fit(y, augment=True)
    val_mask_gen = mask_data_gen.flow(y, batch_size=batch_size, subset='validation')
    
    val_generator = zip(val_img_gen, val_mask_gen)
```

but it gives me:

```

  File "/home/ggous/miniconda3/envs/dpl/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 146, in update_params
    params.update({"cols": kwargs["image"].shape[1], "rows": kwargs["image"].shape[0]})

KeyError: 'image'
```

when calling ` mask_data_gen.fit(y, augment=True)`

**Comment by mjkvaak** [comment]
Hi! Thanks for bringing up this bug and sorry for the late response. The issue has now been fixed in the latest commit (`eab095f24e5344c9c7b285f3f6c2fef70718de51`).  

Please be mindful that, while performing the fit-transform on your targets might actually be what you wanted to do, it may also be something that you should not do. From the fact that you are doing segmentation, my guess would be that you don't actually want to normalize your targets. Notice also, that `.fit` is only required, if `featurewise_center` or `featurewise_std_normalization` or `zca_whitening` are set to `True`. In your code, you did not specify any of these.

**Comment by ggous** [comment]
Ok, thank you very much!
Runs fine now!
 
A question. Why don't we need to normalize our targets during segmentation? It's because we are using albumentations and these require an un-normalized image?

**Comment by mjkvaak** [comment]
To answer your question, whether or not the normalization is required depends on what you try to aim. If you are training a model for img2img transfer with continuous-valued targets, such as grayscale to rgb (i.e. color retrieval with NNs), then normalization is justified. If, on the other hand, you are aiming to do instance segmentation (pixelwise classification), which I guess you are doing because you are involving the `one_hot_encode_masks`-function, then normalization would not make sense, since the different objects are labelled as ones in the different channels of the output tensor. Namely, normalization would shift the values of these ground truth values that are intended to have 0=background, 1=instance of interest. Hope this makes sense. 

However, in reality, the `.fit` would not do actually anything in your above code, since all `featurewise_center` or `featurewise_std_normalization` or `zca_whitening` (options that would actually do the transformations) are defaulting to `False`.

**Comment by ggous** [comment]
I am using it for object detection. Multiple same class objects in image.
